/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Whitepaper08TresDiasRouteImport } from './routes/whitepaper-08-tres-dias'
import { Route as Whitepaper07PreAuditoriaIntegradaRouteImport } from './routes/whitepaper-07-pre-auditoria-integrada'
import { Route as Whitepaper06DoGabineteAoTerminalRouteImport } from './routes/whitepaper-06-do-gabinete-ao-terminal'
import { Route as Whitepaper05QuandoAMaquinaEntraNaSalaRouteImport } from './routes/whitepaper-05-quando-a-maquina-entra-na-sala'
import { Route as Whitepaper04OQueAMaquinaEncontrouRouteImport } from './routes/whitepaper-04-o-que-a-maquina-encontrou'
import { Route as Whitepaper03DeliberacoesEPrimeirosAchadosRouteImport } from './routes/whitepaper-03-deliberacoes-e-primeiros-achados'
import { Route as Whitepaper02CustoEControleRouteImport } from './routes/whitepaper-02-custo-e-controle'
import { Route as Whitepaper01ExtracaoCauprRouteImport } from './routes/whitepaper-01-extracao-caupr'
import { Route as TestemodeloRouteImport } from './routes/testemodelo'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SolicitarAcessoRouteImport } from './routes/solicitar-acesso'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PnlLoginRouteImport } from './routes/pnl-login'
import { Route as PnlRouteImport } from './routes/pnl'
import { Route as PatrocineRouteImport } from './routes/patrocine'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EscalaRouteImport } from './routes/escala'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApoiarRouteImport } from './routes/apoiar'
import { Route as ApagarRouteImport } from './routes/apagar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PnlIndexRouteImport } from './routes/pnl/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PnlUsuariosRouteImport } from './routes/pnl/usuarios'
import { Route as PnlPipelineRouteImport } from './routes/pnl/pipeline'
import { Route as PnlFinanceiroRouteImport } from './routes/pnl/financeiro'
import { Route as PnlDashboardRouteImport } from './routes/pnl/dashboard'
import { Route as PainelChatRouteImport } from './routes/painel/chat'
import { Route as PainelSlugRouteImport } from './routes/painel/$slug'
import { Route as PainelSlugIndexRouteImport } from './routes/painel/$slug/index'
import { Route as PainelSlugAtoIdRouteImport } from './routes/painel/$slug/ato.$id'

const Whitepaper08TresDiasRoute = Whitepaper08TresDiasRouteImport.update({
  id: '/whitepaper-08-tres-dias',
  path: '/whitepaper-08-tres-dias',
  getParentRoute: () => rootRouteImport,
} as any)
const Whitepaper07PreAuditoriaIntegradaRoute =
  Whitepaper07PreAuditoriaIntegradaRouteImport.update({
    id: '/whitepaper-07-pre-auditoria-integrada',
    path: '/whitepaper-07-pre-auditoria-integrada',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper06DoGabineteAoTerminalRoute =
  Whitepaper06DoGabineteAoTerminalRouteImport.update({
    id: '/whitepaper-06-do-gabinete-ao-terminal',
    path: '/whitepaper-06-do-gabinete-ao-terminal',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper05QuandoAMaquinaEntraNaSalaRoute =
  Whitepaper05QuandoAMaquinaEntraNaSalaRouteImport.update({
    id: '/whitepaper-05-quando-a-maquina-entra-na-sala',
    path: '/whitepaper-05-quando-a-maquina-entra-na-sala',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper04OQueAMaquinaEncontrouRoute =
  Whitepaper04OQueAMaquinaEncontrouRouteImport.update({
    id: '/whitepaper-04-o-que-a-maquina-encontrou',
    path: '/whitepaper-04-o-que-a-maquina-encontrou',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper03DeliberacoesEPrimeirosAchadosRoute =
  Whitepaper03DeliberacoesEPrimeirosAchadosRouteImport.update({
    id: '/whitepaper-03-deliberacoes-e-primeiros-achados',
    path: '/whitepaper-03-deliberacoes-e-primeiros-achados',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper02CustoEControleRoute =
  Whitepaper02CustoEControleRouteImport.update({
    id: '/whitepaper-02-custo-e-controle',
    path: '/whitepaper-02-custo-e-controle',
    getParentRoute: () => rootRouteImport,
  } as any)
const Whitepaper01ExtracaoCauprRoute =
  Whitepaper01ExtracaoCauprRouteImport.update({
    id: '/whitepaper-01-extracao-caupr',
    path: '/whitepaper-01-extracao-caupr',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestemodeloRoute = TestemodeloRouteImport.update({
  id: '/testemodelo',
  path: '/testemodelo',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarAcessoRoute = SolicitarAcessoRouteImport.update({
  id: '/solicitar-acesso',
  path: '/solicitar-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlLoginRoute = PnlLoginRouteImport.update({
  id: '/pnl-login',
  path: '/pnl-login',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlRoute = PnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocineRoute = PatrocineRouteImport.update({
  id: '/patrocine',
  path: '/patrocine',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalaRoute = EscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarRoute = ApoiarRouteImport.update({
  id: '/apoiar',
  path: '/apoiar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApagarRoute = ApagarRouteImport.update({
  id: '/apagar',
  path: '/apagar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PnlIndexRoute = PnlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PnlRoute,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PnlUsuariosRoute = PnlUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PnlRoute,
} as any)
const PnlPipelineRoute = PnlPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => PnlRoute,
} as any)
const PnlFinanceiroRoute = PnlFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => PnlRoute,
} as any)
const PnlDashboardRoute = PnlDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PnlRoute,
} as any)
const PainelChatRoute = PainelChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSlugRoute = PainelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSlugIndexRoute = PainelSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelSlugRoute,
} as any)
const PainelSlugAtoIdRoute = PainelSlugAtoIdRouteImport.update({
  id: '/ato/$id',
  path: '/ato/$id',
  getParentRoute: () => PainelSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apagar': typeof ApagarRoute
  '/apoiar': typeof ApoiarRoute
  '/blog': typeof BlogRoute
  '/entrar': typeof EntrarRoute
  '/escala': typeof EscalaRoute
  '/explorar': typeof ExplorarRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRouteWithChildren
  '/patrocine': typeof PatrocineRoute
  '/pnl': typeof PnlRouteWithChildren
  '/pnl-login': typeof PnlLoginRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solicitar-acesso': typeof SolicitarAcessoRoute
  '/solucoes': typeof SolucoesRoute
  '/testemodelo': typeof TestemodeloRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
  '/whitepaper-02-custo-e-controle': typeof Whitepaper02CustoEControleRoute
  '/whitepaper-03-deliberacoes-e-primeiros-achados': typeof Whitepaper03DeliberacoesEPrimeirosAchadosRoute
  '/whitepaper-04-o-que-a-maquina-encontrou': typeof Whitepaper04OQueAMaquinaEncontrouRoute
  '/whitepaper-05-quando-a-maquina-entra-na-sala': typeof Whitepaper05QuandoAMaquinaEntraNaSalaRoute
  '/whitepaper-06-do-gabinete-ao-terminal': typeof Whitepaper06DoGabineteAoTerminalRoute
  '/whitepaper-07-pre-auditoria-integrada': typeof Whitepaper07PreAuditoriaIntegradaRoute
  '/whitepaper-08-tres-dias': typeof Whitepaper08TresDiasRoute
  '/painel/$slug': typeof PainelSlugRouteWithChildren
  '/painel/chat': typeof PainelChatRoute
  '/pnl/dashboard': typeof PnlDashboardRoute
  '/pnl/financeiro': typeof PnlFinanceiroRoute
  '/pnl/pipeline': typeof PnlPipelineRoute
  '/pnl/usuarios': typeof PnlUsuariosRoute
  '/painel/': typeof PainelIndexRoute
  '/pnl/': typeof PnlIndexRoute
  '/painel/$slug/': typeof PainelSlugIndexRoute
  '/painel/$slug/ato/$id': typeof PainelSlugAtoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apagar': typeof ApagarRoute
  '/apoiar': typeof ApoiarRoute
  '/blog': typeof BlogRoute
  '/entrar': typeof EntrarRoute
  '/escala': typeof EscalaRoute
  '/explorar': typeof ExplorarRoute
  '/modelos': typeof ModelosRoute
  '/patrocine': typeof PatrocineRoute
  '/pnl-login': typeof PnlLoginRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solicitar-acesso': typeof SolicitarAcessoRoute
  '/solucoes': typeof SolucoesRoute
  '/testemodelo': typeof TestemodeloRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
  '/whitepaper-02-custo-e-controle': typeof Whitepaper02CustoEControleRoute
  '/whitepaper-03-deliberacoes-e-primeiros-achados': typeof Whitepaper03DeliberacoesEPrimeirosAchadosRoute
  '/whitepaper-04-o-que-a-maquina-encontrou': typeof Whitepaper04OQueAMaquinaEncontrouRoute
  '/whitepaper-05-quando-a-maquina-entra-na-sala': typeof Whitepaper05QuandoAMaquinaEntraNaSalaRoute
  '/whitepaper-06-do-gabinete-ao-terminal': typeof Whitepaper06DoGabineteAoTerminalRoute
  '/whitepaper-07-pre-auditoria-integrada': typeof Whitepaper07PreAuditoriaIntegradaRoute
  '/whitepaper-08-tres-dias': typeof Whitepaper08TresDiasRoute
  '/painel/chat': typeof PainelChatRoute
  '/pnl/dashboard': typeof PnlDashboardRoute
  '/pnl/financeiro': typeof PnlFinanceiroRoute
  '/pnl/pipeline': typeof PnlPipelineRoute
  '/pnl/usuarios': typeof PnlUsuariosRoute
  '/painel': typeof PainelIndexRoute
  '/pnl': typeof PnlIndexRoute
  '/painel/$slug': typeof PainelSlugIndexRoute
  '/painel/$slug/ato/$id': typeof PainelSlugAtoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apagar': typeof ApagarRoute
  '/apoiar': typeof ApoiarRoute
  '/blog': typeof BlogRoute
  '/entrar': typeof EntrarRoute
  '/escala': typeof EscalaRoute
  '/explorar': typeof ExplorarRoute
  '/modelos': typeof ModelosRoute
  '/painel': typeof PainelRouteWithChildren
  '/patrocine': typeof PatrocineRoute
  '/pnl': typeof PnlRouteWithChildren
  '/pnl-login': typeof PnlLoginRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solicitar-acesso': typeof SolicitarAcessoRoute
  '/solucoes': typeof SolucoesRoute
  '/testemodelo': typeof TestemodeloRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
  '/whitepaper-02-custo-e-controle': typeof Whitepaper02CustoEControleRoute
  '/whitepaper-03-deliberacoes-e-primeiros-achados': typeof Whitepaper03DeliberacoesEPrimeirosAchadosRoute
  '/whitepaper-04-o-que-a-maquina-encontrou': typeof Whitepaper04OQueAMaquinaEncontrouRoute
  '/whitepaper-05-quando-a-maquina-entra-na-sala': typeof Whitepaper05QuandoAMaquinaEntraNaSalaRoute
  '/whitepaper-06-do-gabinete-ao-terminal': typeof Whitepaper06DoGabineteAoTerminalRoute
  '/whitepaper-07-pre-auditoria-integrada': typeof Whitepaper07PreAuditoriaIntegradaRoute
  '/whitepaper-08-tres-dias': typeof Whitepaper08TresDiasRoute
  '/painel/$slug': typeof PainelSlugRouteWithChildren
  '/painel/chat': typeof PainelChatRoute
  '/pnl/dashboard': typeof PnlDashboardRoute
  '/pnl/financeiro': typeof PnlFinanceiroRoute
  '/pnl/pipeline': typeof PnlPipelineRoute
  '/pnl/usuarios': typeof PnlUsuariosRoute
  '/painel/': typeof PainelIndexRoute
  '/pnl/': typeof PnlIndexRoute
  '/painel/$slug/': typeof PainelSlugIndexRoute
  '/painel/$slug/ato/$id': typeof PainelSlugAtoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apagar'
    | '/apoiar'
    | '/blog'
    | '/entrar'
    | '/escala'
    | '/explorar'
    | '/modelos'
    | '/painel'
    | '/patrocine'
    | '/pnl'
    | '/pnl-login'
    | '/precos'
    | '/produto'
    | '/solicitar-acesso'
    | '/solucoes'
    | '/testemodelo'
    | '/whitepaper-01-extracao-caupr'
    | '/whitepaper-02-custo-e-controle'
    | '/whitepaper-03-deliberacoes-e-primeiros-achados'
    | '/whitepaper-04-o-que-a-maquina-encontrou'
    | '/whitepaper-05-quando-a-maquina-entra-na-sala'
    | '/whitepaper-06-do-gabinete-ao-terminal'
    | '/whitepaper-07-pre-auditoria-integrada'
    | '/whitepaper-08-tres-dias'
    | '/painel/$slug'
    | '/painel/chat'
    | '/pnl/dashboard'
    | '/pnl/financeiro'
    | '/pnl/pipeline'
    | '/pnl/usuarios'
    | '/painel/'
    | '/pnl/'
    | '/painel/$slug/'
    | '/painel/$slug/ato/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apagar'
    | '/apoiar'
    | '/blog'
    | '/entrar'
    | '/escala'
    | '/explorar'
    | '/modelos'
    | '/patrocine'
    | '/pnl-login'
    | '/precos'
    | '/produto'
    | '/solicitar-acesso'
    | '/solucoes'
    | '/testemodelo'
    | '/whitepaper-01-extracao-caupr'
    | '/whitepaper-02-custo-e-controle'
    | '/whitepaper-03-deliberacoes-e-primeiros-achados'
    | '/whitepaper-04-o-que-a-maquina-encontrou'
    | '/whitepaper-05-quando-a-maquina-entra-na-sala'
    | '/whitepaper-06-do-gabinete-ao-terminal'
    | '/whitepaper-07-pre-auditoria-integrada'
    | '/whitepaper-08-tres-dias'
    | '/painel/chat'
    | '/pnl/dashboard'
    | '/pnl/financeiro'
    | '/pnl/pipeline'
    | '/pnl/usuarios'
    | '/painel'
    | '/pnl'
    | '/painel/$slug'
    | '/painel/$slug/ato/$id'
  id:
    | '__root__'
    | '/'
    | '/apagar'
    | '/apoiar'
    | '/blog'
    | '/entrar'
    | '/escala'
    | '/explorar'
    | '/modelos'
    | '/painel'
    | '/patrocine'
    | '/pnl'
    | '/pnl-login'
    | '/precos'
    | '/produto'
    | '/solicitar-acesso'
    | '/solucoes'
    | '/testemodelo'
    | '/whitepaper-01-extracao-caupr'
    | '/whitepaper-02-custo-e-controle'
    | '/whitepaper-03-deliberacoes-e-primeiros-achados'
    | '/whitepaper-04-o-que-a-maquina-encontrou'
    | '/whitepaper-05-quando-a-maquina-entra-na-sala'
    | '/whitepaper-06-do-gabinete-ao-terminal'
    | '/whitepaper-07-pre-auditoria-integrada'
    | '/whitepaper-08-tres-dias'
    | '/painel/$slug'
    | '/painel/chat'
    | '/pnl/dashboard'
    | '/pnl/financeiro'
    | '/pnl/pipeline'
    | '/pnl/usuarios'
    | '/painel/'
    | '/pnl/'
    | '/painel/$slug/'
    | '/painel/$slug/ato/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApagarRoute: typeof ApagarRoute
  ApoiarRoute: typeof ApoiarRoute
  BlogRoute: typeof BlogRoute
  EntrarRoute: typeof EntrarRoute
  EscalaRoute: typeof EscalaRoute
  ExplorarRoute: typeof ExplorarRoute
  ModelosRoute: typeof ModelosRoute
  PainelRoute: typeof PainelRouteWithChildren
  PatrocineRoute: typeof PatrocineRoute
  PnlRoute: typeof PnlRouteWithChildren
  PnlLoginRoute: typeof PnlLoginRoute
  PrecosRoute: typeof PrecosRoute
  ProdutoRoute: typeof ProdutoRoute
  SolicitarAcessoRoute: typeof SolicitarAcessoRoute
  SolucoesRoute: typeof SolucoesRoute
  TestemodeloRoute: typeof TestemodeloRoute
  Whitepaper01ExtracaoCauprRoute: typeof Whitepaper01ExtracaoCauprRoute
  Whitepaper02CustoEControleRoute: typeof Whitepaper02CustoEControleRoute
  Whitepaper03DeliberacoesEPrimeirosAchadosRoute: typeof Whitepaper03DeliberacoesEPrimeirosAchadosRoute
  Whitepaper04OQueAMaquinaEncontrouRoute: typeof Whitepaper04OQueAMaquinaEncontrouRoute
  Whitepaper05QuandoAMaquinaEntraNaSalaRoute: typeof Whitepaper05QuandoAMaquinaEntraNaSalaRoute
  Whitepaper06DoGabineteAoTerminalRoute: typeof Whitepaper06DoGabineteAoTerminalRoute
  Whitepaper07PreAuditoriaIntegradaRoute: typeof Whitepaper07PreAuditoriaIntegradaRoute
  Whitepaper08TresDiasRoute: typeof Whitepaper08TresDiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper-08-tres-dias': {
      id: '/whitepaper-08-tres-dias'
      path: '/whitepaper-08-tres-dias'
      fullPath: '/whitepaper-08-tres-dias'
      preLoaderRoute: typeof Whitepaper08TresDiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-07-pre-auditoria-integrada': {
      id: '/whitepaper-07-pre-auditoria-integrada'
      path: '/whitepaper-07-pre-auditoria-integrada'
      fullPath: '/whitepaper-07-pre-auditoria-integrada'
      preLoaderRoute: typeof Whitepaper07PreAuditoriaIntegradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-06-do-gabinete-ao-terminal': {
      id: '/whitepaper-06-do-gabinete-ao-terminal'
      path: '/whitepaper-06-do-gabinete-ao-terminal'
      fullPath: '/whitepaper-06-do-gabinete-ao-terminal'
      preLoaderRoute: typeof Whitepaper06DoGabineteAoTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-05-quando-a-maquina-entra-na-sala': {
      id: '/whitepaper-05-quando-a-maquina-entra-na-sala'
      path: '/whitepaper-05-quando-a-maquina-entra-na-sala'
      fullPath: '/whitepaper-05-quando-a-maquina-entra-na-sala'
      preLoaderRoute: typeof Whitepaper05QuandoAMaquinaEntraNaSalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-04-o-que-a-maquina-encontrou': {
      id: '/whitepaper-04-o-que-a-maquina-encontrou'
      path: '/whitepaper-04-o-que-a-maquina-encontrou'
      fullPath: '/whitepaper-04-o-que-a-maquina-encontrou'
      preLoaderRoute: typeof Whitepaper04OQueAMaquinaEncontrouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-03-deliberacoes-e-primeiros-achados': {
      id: '/whitepaper-03-deliberacoes-e-primeiros-achados'
      path: '/whitepaper-03-deliberacoes-e-primeiros-achados'
      fullPath: '/whitepaper-03-deliberacoes-e-primeiros-achados'
      preLoaderRoute: typeof Whitepaper03DeliberacoesEPrimeirosAchadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-02-custo-e-controle': {
      id: '/whitepaper-02-custo-e-controle'
      path: '/whitepaper-02-custo-e-controle'
      fullPath: '/whitepaper-02-custo-e-controle'
      preLoaderRoute: typeof Whitepaper02CustoEControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper-01-extracao-caupr': {
      id: '/whitepaper-01-extracao-caupr'
      path: '/whitepaper-01-extracao-caupr'
      fullPath: '/whitepaper-01-extracao-caupr'
      preLoaderRoute: typeof Whitepaper01ExtracaoCauprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testemodelo': {
      id: '/testemodelo'
      path: '/testemodelo'
      fullPath: '/testemodelo'
      preLoaderRoute: typeof TestemodeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-acesso': {
      id: '/solicitar-acesso'
      path: '/solicitar-acesso'
      fullPath: '/solicitar-acesso'
      preLoaderRoute: typeof SolicitarAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl-login': {
      id: '/pnl-login'
      path: '/pnl-login'
      fullPath: '/pnl-login'
      preLoaderRoute: typeof PnlLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl': {
      id: '/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof PnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocine': {
      id: '/patrocine'
      path: '/patrocine'
      fullPath: '/patrocine'
      preLoaderRoute: typeof PatrocineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escala': {
      id: '/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof EscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar': {
      id: '/apoiar'
      path: '/apoiar'
      fullPath: '/apoiar'
      preLoaderRoute: typeof ApoiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apagar': {
      id: '/apagar'
      path: '/apagar'
      fullPath: '/apagar'
      preLoaderRoute: typeof ApagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnl/': {
      id: '/pnl/'
      path: '/'
      fullPath: '/pnl/'
      preLoaderRoute: typeof PnlIndexRouteImport
      parentRoute: typeof PnlRoute
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/pnl/usuarios': {
      id: '/pnl/usuarios'
      path: '/usuarios'
      fullPath: '/pnl/usuarios'
      preLoaderRoute: typeof PnlUsuariosRouteImport
      parentRoute: typeof PnlRoute
    }
    '/pnl/pipeline': {
      id: '/pnl/pipeline'
      path: '/pipeline'
      fullPath: '/pnl/pipeline'
      preLoaderRoute: typeof PnlPipelineRouteImport
      parentRoute: typeof PnlRoute
    }
    '/pnl/financeiro': {
      id: '/pnl/financeiro'
      path: '/financeiro'
      fullPath: '/pnl/financeiro'
      preLoaderRoute: typeof PnlFinanceiroRouteImport
      parentRoute: typeof PnlRoute
    }
    '/pnl/dashboard': {
      id: '/pnl/dashboard'
      path: '/dashboard'
      fullPath: '/pnl/dashboard'
      preLoaderRoute: typeof PnlDashboardRouteImport
      parentRoute: typeof PnlRoute
    }
    '/painel/chat': {
      id: '/painel/chat'
      path: '/chat'
      fullPath: '/painel/chat'
      preLoaderRoute: typeof PainelChatRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$slug': {
      id: '/painel/$slug'
      path: '/$slug'
      fullPath: '/painel/$slug'
      preLoaderRoute: typeof PainelSlugRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$slug/': {
      id: '/painel/$slug/'
      path: '/'
      fullPath: '/painel/$slug/'
      preLoaderRoute: typeof PainelSlugIndexRouteImport
      parentRoute: typeof PainelSlugRoute
    }
    '/painel/$slug/ato/$id': {
      id: '/painel/$slug/ato/$id'
      path: '/ato/$id'
      fullPath: '/painel/$slug/ato/$id'
      preLoaderRoute: typeof PainelSlugAtoIdRouteImport
      parentRoute: typeof PainelSlugRoute
    }
  }
}

interface PainelSlugRouteChildren {
  PainelSlugIndexRoute: typeof PainelSlugIndexRoute
  PainelSlugAtoIdRoute: typeof PainelSlugAtoIdRoute
}

const PainelSlugRouteChildren: PainelSlugRouteChildren = {
  PainelSlugIndexRoute: PainelSlugIndexRoute,
  PainelSlugAtoIdRoute: PainelSlugAtoIdRoute,
}

const PainelSlugRouteWithChildren = PainelSlugRoute._addFileChildren(
  PainelSlugRouteChildren,
)

interface PainelRouteChildren {
  PainelSlugRoute: typeof PainelSlugRouteWithChildren
  PainelChatRoute: typeof PainelChatRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelSlugRoute: PainelSlugRouteWithChildren,
  PainelChatRoute: PainelChatRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

interface PnlRouteChildren {
  PnlDashboardRoute: typeof PnlDashboardRoute
  PnlFinanceiroRoute: typeof PnlFinanceiroRoute
  PnlPipelineRoute: typeof PnlPipelineRoute
  PnlUsuariosRoute: typeof PnlUsuariosRoute
  PnlIndexRoute: typeof PnlIndexRoute
}

const PnlRouteChildren: PnlRouteChildren = {
  PnlDashboardRoute: PnlDashboardRoute,
  PnlFinanceiroRoute: PnlFinanceiroRoute,
  PnlPipelineRoute: PnlPipelineRoute,
  PnlUsuariosRoute: PnlUsuariosRoute,
  PnlIndexRoute: PnlIndexRoute,
}

const PnlRouteWithChildren = PnlRoute._addFileChildren(PnlRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApagarRoute: ApagarRoute,
  ApoiarRoute: ApoiarRoute,
  BlogRoute: BlogRoute,
  EntrarRoute: EntrarRoute,
  EscalaRoute: EscalaRoute,
  ExplorarRoute: ExplorarRoute,
  ModelosRoute: ModelosRoute,
  PainelRoute: PainelRouteWithChildren,
  PatrocineRoute: PatrocineRoute,
  PnlRoute: PnlRouteWithChildren,
  PnlLoginRoute: PnlLoginRoute,
  PrecosRoute: PrecosRoute,
  ProdutoRoute: ProdutoRoute,
  SolicitarAcessoRoute: SolicitarAcessoRoute,
  SolucoesRoute: SolucoesRoute,
  TestemodeloRoute: TestemodeloRoute,
  Whitepaper01ExtracaoCauprRoute: Whitepaper01ExtracaoCauprRoute,
  Whitepaper02CustoEControleRoute: Whitepaper02CustoEControleRoute,
  Whitepaper03DeliberacoesEPrimeirosAchadosRoute:
    Whitepaper03DeliberacoesEPrimeirosAchadosRoute,
  Whitepaper04OQueAMaquinaEncontrouRoute:
    Whitepaper04OQueAMaquinaEncontrouRoute,
  Whitepaper05QuandoAMaquinaEntraNaSalaRoute:
    Whitepaper05QuandoAMaquinaEntraNaSalaRoute,
  Whitepaper06DoGabineteAoTerminalRoute: Whitepaper06DoGabineteAoTerminalRoute,
  Whitepaper07PreAuditoriaIntegradaRoute:
    Whitepaper07PreAuditoriaIntegradaRoute,
  Whitepaper08TresDiasRoute: Whitepaper08TresDiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
