/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PatrocineRouteImport } from './routes/patrocine'
import { Route as IndexRouteImport } from './routes/index'

const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocineRoute = PatrocineRouteImport.update({
  id: '/patrocine',
  path: '/patrocine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patrocine' | '/precos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patrocine' | '/precos'
  id: '__root__' | '/' | '/patrocine' | '/precos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatrocineRoute: typeof PatrocineRoute
  PrecosRoute: typeof PrecosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocine': {
      id: '/patrocine'
      path: '/patrocine'
      fullPath: '/patrocine'
      preLoaderRoute: typeof PatrocineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatrocineRoute: PatrocineRoute,
  PrecosRoute: PrecosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
