/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Whitepaper01ExtracaoCauprRouteImport } from './routes/whitepaper-01-extracao-caupr'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PatrocineRouteImport } from './routes/patrocine'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndexRouteImport } from './routes/index'

const Whitepaper01ExtracaoCauprRoute =
  Whitepaper01ExtracaoCauprRouteImport.update({
    id: '/whitepaper-01-extracao-caupr',
    path: '/whitepaper-01-extracao-caupr',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocineRoute = PatrocineRouteImport.update({
  id: '/patrocine',
  path: '/patrocine',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solucoes': typeof SolucoesRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solucoes': typeof SolucoesRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/patrocine': typeof PatrocineRoute
  '/precos': typeof PrecosRoute
  '/produto': typeof ProdutoRoute
  '/solucoes': typeof SolucoesRoute
  '/whitepaper-01-extracao-caupr': typeof Whitepaper01ExtracaoCauprRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/patrocine'
    | '/precos'
    | '/produto'
    | '/solucoes'
    | '/whitepaper-01-extracao-caupr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/patrocine'
    | '/precos'
    | '/produto'
    | '/solucoes'
    | '/whitepaper-01-extracao-caupr'
  id:
    | '__root__'
    | '/'
    | '/entrar'
    | '/patrocine'
    | '/precos'
    | '/produto'
    | '/solucoes'
    | '/whitepaper-01-extracao-caupr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrarRoute: typeof EntrarRoute
  PatrocineRoute: typeof PatrocineRoute
  PrecosRoute: typeof PrecosRoute
  ProdutoRoute: typeof ProdutoRoute
  SolucoesRoute: typeof SolucoesRoute
  Whitepaper01ExtracaoCauprRoute: typeof Whitepaper01ExtracaoCauprRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper-01-extracao-caupr': {
      id: '/whitepaper-01-extracao-caupr'
      path: '/whitepaper-01-extracao-caupr'
      fullPath: '/whitepaper-01-extracao-caupr'
      preLoaderRoute: typeof Whitepaper01ExtracaoCauprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocine': {
      id: '/patrocine'
      path: '/patrocine'
      fullPath: '/patrocine'
      preLoaderRoute: typeof PatrocineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrarRoute: EntrarRoute,
  PatrocineRoute: PatrocineRoute,
  PrecosRoute: PrecosRoute,
  ProdutoRoute: ProdutoRoute,
  SolucoesRoute: SolucoesRoute,
  Whitepaper01ExtracaoCauprRoute: Whitepaper01ExtracaoCauprRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
